# Generated by Django 4.2.7 on 2023-11-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_building', models.CharField(max_length=50)),
                ('rooms', models.PositiveIntegerField()),
                ('area_rooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('area_bathrooms', models.PositiveIntegerField()),
                ('typ_of_cleaning', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=50)),
            ],
        ),
    ]
