# Generated by Django 4.2.7 on 2023-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='area_bathrooms',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='area_rooms',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='bathrooms',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='rooms',
            field=models.CharField(max_length=50),
        ),
    ]
