# Generated by Django 4.2.7 on 2023-11-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_remove_form_area_bathrooms_form_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
