# Generated by Django 4.2.7 on 2023-11-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_form_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='typ_building',
            new_name='type_building',
        ),
    ]
