# Generated by Django 4.2.7 on 2023-11-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0016_alter_form_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='services',
        ),
    ]
