# Generated by Django 4.2.7 on 2023-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0017_remove_form_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
