# Generated by Django 4.2.7 on 2023-11-28 09:50

from django.db import migrations, models

# def create_languages_data(apps, schema_editor):
#     from Languages.models import create_languages
#     create_languages()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_all', models.JSONField()),
            ],
        ),
    ]
